### ISSUE TITLE
jmeter.save.saveservice.timestamp_format=none has no effect on result naming

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#10]

**Comment by djangofan** [comment]
@foragerr Using version 0.1.5, the reports are generating but I am having the issue still where the "jmeter.save.saveservice.timestamp_format=none" property seems to be ignored by this Gradle plugin. I am still getting a report.html that is stamped with a timestamp  and was expecting no timestamp to be in the filename.

I'm using this project to reproduce the issue:
https://github.com/djangofan/launch-jmeter

And yes, if you create a GitHub project that is a 'sample project' for the jmeter-gradle-plugin,  I would certainly help you maintain the examples and use them to QA the plugin.

**Comment by djangofan** [comment]
I just wanted to add 2 more things that would be nice:
1.  the timestamp did not appear on any of the .png or .csv output files either.  
2.  the project '.jmx' file extension did not appear in the names either.

**Comment by foragerr** [comment]
I already sent you an invite to join the contributor team. It says the invite goes out by email..?

**Comment by foragerr** [comment]
Sort of closed this in v0.1.6. Allowed values for `jmeter.save.saveservice.timestamp_format` are `none`, `ms`, or a format suitable for SimpleDateFormat. The plugin now supports `none` and simpleDateFormat, but not `ms`

**Comment by djangofan** [comment]
@foragerr   Ok, I just tried v0.1.6.   Didn't notice this until now, but whenever I set 'jmeter.save.saveservice.timestamp_format=none'  in the  `src/test/jmeter/jmeter.properties`  file,  when Gradle runs the build, it is failing to generate a 'interpolated' (that means a shortened file without comments) jmeter.properties file in the  location `build/jmeter/jmeter.properties`  .  Instead , what it does is copy/overwrite a new 'default'  jmeter.properties file.  Therefore, when it runs, I am now unable to set that property to 'none'.   Even when I remove the 'clean' phase from my Gradle build, same thing.   Can you verify?  It's easy to reproduce with my above-mentioned project.

Also, I am now noticing that the  `src/test/jmeter/user.properties` file does not get copied into place in the `build/jmeter/user.properties` as it probably should .

I tried this in my build.gradle and it didn't work for me either:
`jmeterRun.configure {`
`jmeterUserProperties = []`
`jmeterUserProperties << "jmeter.save.saveservice.timestamp_format=none"`

This problem copying the property files into place might be part of the problem here?

**Comment by foragerr** [comment]
The plugin should only copy over 'default' jmeter.properties if there isn't a user defined one. So this behavior is definitely a defect.

**Comment by djangofan** [comment]
@foragerr   Ok, I entered a separate issue #12 for that problem.   Just so you know, I cannot sign off that this issue (#10)  is fixed until that one is fixed first.    Resolution of issue #10 requires resolution of issue #12 .

**Comment by djangofan** [comment]
Just as a FYI:  issue still exists in version 0.5.6 of the plugin.

**Comment by djangofan** [comment]
Just a FYI: problem still exists in version 0.6.3 of the plugin  when  `jmeter.save.saveservice.timestamp_format=none`  is set in  `src/test/jmeter/jmeter.properties` file.   Since `build/jmeter/jmeter.properties` does not properly copy this property from the former location, it appears that is the cause of the problem but we won't know for sure until we fix item #12 .

**Comment by foragerr** [comment]
> problem still exists

The defect status is still open, it hasn't been fixed yet.

**Comment by foragerr** [comment]
Added new plugin option `resultsLog` that maps to JMeter option `-l`. This option allows user to name the result log file however they want. Removing other result name customization options from the plugin. save service naming properties are not used in results naming anymore.
