### ISSUE TITLE
how to change srcDir property value

### ISSUE THREAD

**Issue by cfalba80** [jmeter-gradle-plugin/jmeter-gradle-plugin#19]
the srcDir property present in the previous plugin repository seems to be not working here, please show an example on how to change it here.
Thanks.

**Comment by foragerr** [comment]
There isn't a way to add an entire directory as `srcDir` but it is possible to list all your jmx files using:

```
jmeter {
    jmTestFiles = [file("path/to/nonDefaultLocation.jmx"),
    file("path/to/nonDefaultLocation2.jmx"),
    file("path/to/nonDefaultLocation3.jmx")] 
}
```

Is this sufficient for your need?

**Comment by djangofan** [comment]
@foragerr  In reply to previous comment above, if adding "file" entries is too "arduous", its simple enough to just write a few lines of Groovy code to assemble the list of files.  I see no reason to have the Gradle plugin do a *.jmx scan of the folder to include all files by default.

Have a default scan of the folder to include all files would be problematic for me since I might want different "gradle profiles" that run different sets of tests.  It would be undesirable behavior despite the fact that Kulya may have implemented it that way.   Additionally, not that it matters much, but the Maven jmeter plugin does not scan for files either.

**Comment by foragerr** [comment]
Absolutely agree with you that a line or two of groovy code will produce a list of files. But in the interest of backward compatibility\* and defaulting towards more-choice, I'll allow `testFileDir` (an equivalent of `srcDir`) back into the fold.

To allay your worry however, and to not break your workflow: if you define `jmTestFiles`, it will override `testFileDir` and turn off directory scanning completely.

\* I _do_ want to see users gradually migrate over from the older plugin to this version. If adding this feature makes the switchover less painful for some folks, I think I'll let it pass even if I don't agree completely
