### ISSUE TITLE
Create aggregated HTML for extended reports containing all the generated PNGs and CSVs

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#24]

**Comment by djangofan** [comment]
When you fix this one, please do not alter the existing  '-report.html'  file.   If you want to include a index.html that contains links to all artifacts, please make sure it handles multiple project file outputs.  You might want to keep each project files outputs each in a separate .HTML report .  I would suggest something like this:

```
resultsDir
    |-----  index.html
    |-----  projA
          |----  projA-report.html  (report in style of a typical jmeter report with no external links)
          |----  projA-index.html  (same as above but having links to all related external file artifacts)
          |----  image-abc.png
          |----  file-abc.csv
    |-----  projB
          |-----  projB-report.html
          |-----  projB-index.html
```

Let me emphasize, that when you do this, please retain the ability to  have OR NOT HAVE timestamps on all the file artifacts.    This is important for Jenkins "HTML archive" plugin, which can only archive one file at a time.

**Comment by foragerr** [comment]
Partially implemented. A html file generated per result jtl/xml file, so far containing only its PNG images but not CSV data.

**Comment by foragerr** [comment]
@djangofan existing -report.html is generated by the basic reports feature, which stays as is. The new ext-html is generated if extended reports is enabled.

**Comment by djangofan** [comment]
@foragerr  That sounds great.  Thanks.   Just say something here when its all done and I can look at it.

**Comment by foragerr** [comment]
The rest of the weekend looks busy for me, not sure if I'll be able to get anything else in. If you want to try what's been checked in so far, use:

	buildscript {
		repositories {
			mavenCentral()
			maven {
				url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
			}
		}
		dependencies {
			classpath "net.foragerr.jmeter:jmeter-gradle-plugin:+"
		}
	}

From here onwards, any changes checked into master will be immediately available as SNAPSHOTversions on `oss.jfrog.org` - any non-SNAPSHOT versions will be available on bintray and jcenter, and hopefully soon mavenCentral.

**Comment by djangofan** [comment]
@foragerr   I still haven't tested this.  I will try tonight.

**Comment by djangofan** [comment]
Ok, I tried oss-snapshot-local.  I appears I get the same results as I reported from 0.6.3 :

1.  When your build script has 'enableReports=false' , then if you run 'jmReports', the report is built anyway.  When 'enableReports=true', my expectation is that the 'jmRun' task should obey the 'enableReports=true' property and trigger 'jmReports' even when it is not called explicitly.  Also, I would suggest renaming the 'enableReports' property to 'autoGenerateReports=true' or some other name that implies that 'jmRun' also includes the execution report task.  I can think of no better name.

2.  enableExtendedReports = false works as expected.

3.  The 'jmGui' task is failing to load the jmeter plugin packs.  See screenshots here of what the menus should look like:
https://www.dropbox.com/sh/2p9jpdyobvay6wg/AABZd4naxWcCqdwlevaBZrDRa?dl=0
The 'groovy-all.jar', when specified  seems-to-be loaded correctly though when specified as part of jmPluginJars, so that's a good sign, unless you are loading it by another route which I am not noticing.

4.  When the '-report.html' file is generated, it is incorrectly named like so:
   "project.jmx-timestamp.html"  instead of the name it should have had, which is "project.jmx-timestamp-report.html"
 Also, let me suggest that this name would be even better: "project-timestamp-report.html", without the '.jmx' extenstion in the file name.

5.  When 'jmTestFiles' property is not set, the plugin scans and runs multiple project files.  In this use case, multiple '-extReport.html' files are being generated, 1 for each project file, but the regular '-report.html' file is failing to be generated by that name (or any other name).  Needs to be fixed.

**Comment by foragerr** [comment]
Thank you @djangofan !
Tracking each defect separately:

1 -> new #26 

3 -> already tracked in #3 

4 -> new #27

5 -> new #28

**Comment by djangofan** [comment]
Sure.  I'll get more free time soon and I will try to help.  If I fork from the main GitHub project (not from bintray), doing a merge from my fork will work ok right?

**Comment by foragerr** [comment]
Yes, after you make changes in your fork, you have to create a Pull Request - which will allow me to merge changes into the main branch. https://help.github.com/articles/creating-a-pull-request/

More detailed workflow walkthrough: https://help.github.com/articles/using-pull-requests/

You shouldn't be doing anything on bintray.

**Comment by foragerr** [comment]
Implementing Jmeter 3.0's report [dashboard ](http://jmeter.apache.org/usermanual/generating-dashboard.html)instead of this enhancement.
