### ISSUE TITLE
enableReports=false does not disable HTML reports

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#26]

**Comment by foragerr** [comment]
Unable to reproduce using newest SNAPSHOT version: jmeter-gradle-plugin-0.6.3-2.13-20150731.194431-4.jar

Setting

```
    enableReports = false
    enableExtendedReports = false
```

does not produce any reports when `jmReport` is run

**Comment by djangofan** [comment]
@foragerr   Please reopen this.   The reason you dont see anything being generated is because the regular '-report.html' reports are not currently being generated.  I originally noticed this issue before it was broken and so it merely APPEARS that its working, but i would say not likely to actually be true.  I don't remember the exact version I originally tested it in but it may have been over 2-3 weeks ago.

**Comment by foragerr** [comment]
This issue definitely existed earlier. It was fixed here: https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/commit/d9418c70d53828132a67c2d447970135b3231077

please retest with:

```
buildscript {
    repositories {
        mavenCentral()
        maven {url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'}
    }
    dependencies {
        classpath "net.foragerr.jmeter:jmeter-gradle-plugin:+"
    }
}
```

setting `enableReports = true` generates a html report successfully

**Comment by foragerr** [comment]
If you can reproduce this with the config above, let me know, i'll reopen this issue.

**Comment by djangofan** [comment]
When I run with these options:

`enableReports = true
    enableExtendedReports = false`

I get 2 .html reports named like 'test1.jmx-20150806-0752.html'.

When I run with these options:

`enableReports = true
    enableExtendedReports = false`

I end up with the exact same thing.

So, in my mind there are 2 problems with that 'snapshot version':
1.  The resulting .html file name needs to end with  '-report.html', like it did before.
2.  The extended report, which gets generated by version 0.6.3, does not get generated in this snapshot version.

Can you confirm and give me steps to reproduce if you think otherwise?   I am reproducing with the 'jmeter-gradle-adv-example' project.   I cannot verify this bug, as originally described, unless the items above work properly, more-so on item number 2.

**Comment by foragerr** [comment]
let's retest once I do a regular release

**Comment by foragerr** [comment]
@djangofan If you get a chance can you please retest this in 0.6.4?

**Comment by djangofan** [comment]
Yeah.  I'll look

**Comment by foragerr** [comment]
Thank you, sir.

**Comment by djangofan** [comment]
@foragerr  When I run with these options, from https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin-adv-example , the extended reports for both of my project files ARE generated correctly:
        `enableReports = false`
    `enableExtendedReports = true`

BUT, if I run with this configuration at all:
        `enableReports = true`

The main .html reports are not being generated.  There is an exception:
https://gist.github.com/djangofan/12de409e095d9c35d107

Maybe I just need to provide the standard .xslt file, but I don't know where to put it in my project, do you?

**Comment by foragerr** [comment]
No you shouldn't have to provide the XSLT. I'm going to try to reproduce that error.

**Comment by djangofan** [comment]
Yes, by adding this to my build.gradle , it works:
`reportXslt = "src/test/jmeter/jmeter-results-report_21.xsl"`
But, since this is a "required" thing, isn't there anything you can do , like add to the documenation that it is required?   Or perhaps, make the exception thrown tell the user what they need to do?

To re-iterate, if you don't provide the reportXslt option , reports do not get generated, so I am not sure I would agree its fixed.

Thanks for the workaround.

**Comment by foragerr** [comment]
@djangofan  I checked in a change (not released yet). Providing XSLT file will not be required.
