### ISSUE TITLE
Add support for jmeter-plugins 1.3.0

### ISSUE THREAD

**Issue by foragerr** [jmeter-gradle-plugin/jmeter-gradle-plugin#3]
Add support for jmeter-plugins 1.3.0

**Comment by foragerr** [comment]
issue details here: https://github.com/kulya/jmeter-gradle-plugin/issues/56

**Comment by foragerr** [comment]
v0.5.3 uses jmeter-plugins-version 1.3.0 Please verify if this issue still occurs.

**Comment by djangofan** [comment]
In version 0.5.6  there is still some sort of problem where the plugins are not loading.  You can tell because when you open Jmeter, the "add menus" are missing many of the 'jp@c' plugin items.

**Comment by foragerr** [comment]
Could you please post a screenshot of how it should look if it loads right?

**Comment by djangofan** [comment]
In version 0.6.3, the 'jmGui' task is failing to load the jmeter plugin packs. See screenshots here of what the menus should look like:
https://www.dropbox.com/sh/2p9jpdyobvay6wg/AABZd4naxWcCqdwlevaBZrDRa?dl=0
NOTE: The 'groovy-all.jar', as specified in my build.gradle config file, seems-to-be loading correctly though when specified as part of jmPluginJars, so that's a good sign, unless you are loading it by another route which I am not noticing.

**Comment by foragerr** [comment]
Fixed in 1.0.2-SNAPSHOT
will be released in 1.0.2
