### ISSUE TITLE
Support of JMeter 3.1

### ISSUE THREAD

**Issue by Tekketsu** [jmeter-gradle-plugin/jmeter-gradle-plugin#96]
Hello. I'm working with Jmeter 3.1. Will it be supported in the plugin?

**Comment by nicholaspkbowden** [comment]
Jmx files 3.1 and higher are not supported with the current code.
I just made a pull request with code that adds support for jmeter 3.3 and 3.2, however it was rejected due to travis-ci build failure.
The code built locally via command line and eclipse prior to checkin

@foragerr 
Can you provide any support or tips?

Regards,

Nick

**Comment by nicholaspkbowden** [comment]
The pull request adding support for jmeter 3.3 now builds.

@foragerr 
Please approve the pull request

**Comment by foragerr** [comment]
3.3 is now supported

**Comment by pmouawad** [comment]
Hello @foragerr ,
I would suggest for better visibility that you use Milestones and create a new issue and version whenever you support a new JMeter version.

When I look at your project at surface, it looks like last release is 8/21/2016, as a newbie, I might think plugin is outdated while it appears you support 3.3.

Just my 2 cents.

If you want me to help, I'll be happy if you allow me to be an administrator.

Thanks for your work anyway !
Regards
Philippe M.

**Comment by foragerr** [comment]
@pmouawad I do keep release notes on the frontpage readme.md, but I haven't updated it for the 3.3 release. Time has suddenly become scarce :(

Happy to add you as collaborator if you think you have some time to help out!
